ARG PLUGINS_IMG="quay.io/confidential-containers/cloud-provider-plugins:latest"
ARG PEERPOD_CTRL_IMG="quay.io/confidential-containers/peerpod-ctrl:latest"

FROM --platform=$TARGETPLATFORM $PLUGINS_IMG AS plugins
FROM --platform=$TARGETPLATFORM $PEERPOD_CTRL_IMG AS peerpod_ctrl

FROM peerpod_ctrl
COPY --from=plugins /libvirt-ext.so /cloud-providers/libvirt-ext.so
ENTRYPOINT ["/manager"]
